# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from dataclasses import (
    dataclass
)
from typing import (
    TYPE_CHECKING
)
from typing import (
    Literal
)
from typing import (
    Any
)

AuthenticatorId = str

AuthenticatorProtocol = Literal[
    'u2f',
    'ctap2'
]

Ctap2Version = Literal[
    'ctap2_0',
    'ctap2_1'
]

AuthenticatorTransport = Literal[
    'usb',
    'nfc',
    'ble',
    'cable',
    'internal'
]


@dataclass
class VirtualAuthenticatorOptions:
    protocol: 'AuthenticatorProtocol'
    ctap2_version: 'Ctap2Version'
    transport: 'AuthenticatorTransport'
    has_resident_key: bool
    has_user_verification: bool
    has_large_blob: bool
    has_cred_blob: bool
    has_min_pin_length: bool
    has_prf: bool
    automatic_presence_simulation: bool
    is_user_verified: bool


@dataclass
class Credential:
    credential_id: str
    is_resident_credential: bool
    rp_id: str
    private_key: str
    user_handle: str
    sign_count: int
    large_blob: str


@dataclass
class AddVirtualAuthenticatorReturnT:
    authenticator_id: 'AuthenticatorId'


@dataclass
class GetCredentialReturnT:
    credential: 'Credential'


@dataclass
class GetCredentialsReturnT:
    credentials: list
