# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.domains.base import (
    BaseDomain
)
from dataclasses import (
    dataclass
)
from cdp.utils import (
    is_defined,
    UNDEFINED
)
from typing import (
    TYPE_CHECKING
)
from cdp.domains.mapper import (
    from_dict,
    to_dict
)
from cdp.domains.profiler.types import (
    GetBestEffortCoverageReturnT,
    StopReturnT,
    TakePreciseCoverageReturnT,
    TakeTypeProfileReturnT
)
if TYPE_CHECKING:
    from cdp.target.connection import (
        IResponse
    )


@dataclass
class Profiler(BaseDomain):
    def disable(
            self
    ) -> IResponse[None]:
        params = {}

        return self._send_command(
            'Profiler.disable',
            params,
            False
        )

    def enable(
            self
    ) -> IResponse[None]:
        params = {}

        return self._send_command(
            'Profiler.enable',
            params,
            False
        )

    def get_best_effort_coverage(
            self
    ) -> IResponse[GetBestEffortCoverageReturnT]:
        params = {}

        return self._send_command(
            'Profiler.getBestEffortCoverage',
            params,
            True,
            lambda data: from_dict(
                GetBestEffortCoverageReturnT,
                data,
                'camel'
            )
        )

    def set_sampling_interval(
            self,
            interval: 'int'
    ) -> IResponse[None]:
        params = {
            'interval': interval,
        }

        return self._send_command(
            'Profiler.setSamplingInterval',
            params,
            False
        )

    def start(
            self
    ) -> IResponse[None]:
        params = {}

        return self._send_command(
            'Profiler.start',
            params,
            False
        )

    def start_precise_coverage(
            self,
            call_count: 'bool' = UNDEFINED,
            detailed: 'bool' = UNDEFINED
    ) -> IResponse[None]:
        params = {}

        if is_defined(call_count):
            params['callCount'] = call_count

        if is_defined(detailed):
            params['detailed'] = detailed

        return self._send_command(
            'Profiler.startPreciseCoverage',
            params,
            False
        )

    def start_type_profile(
            self
    ) -> IResponse[None]:
        params = {}

        return self._send_command(
            'Profiler.startTypeProfile',
            params,
            False
        )

    def stop(
            self
    ) -> IResponse[StopReturnT]:
        params = {}

        return self._send_command(
            'Profiler.stop',
            params,
            True,
            lambda data: from_dict(
                StopReturnT,
                data,
                'camel'
            )
        )

    def stop_precise_coverage(
            self
    ) -> IResponse[None]:
        params = {}

        return self._send_command(
            'Profiler.stopPreciseCoverage',
            params,
            False
        )

    def stop_type_profile(
            self
    ) -> IResponse[None]:
        params = {}

        return self._send_command(
            'Profiler.stopTypeProfile',
            params,
            False
        )

    def take_precise_coverage(
            self
    ) -> IResponse[TakePreciseCoverageReturnT]:
        params = {}

        return self._send_command(
            'Profiler.takePreciseCoverage',
            params,
            True,
            lambda data: from_dict(
                TakePreciseCoverageReturnT,
                data,
                'camel'
            )
        )

    def take_type_profile(
            self
    ) -> IResponse[TakeTypeProfileReturnT]:
        params = {}

        return self._send_command(
            'Profiler.takeTypeProfile',
            params,
            True,
            lambda data: from_dict(
                TakeTypeProfileReturnT,
                data,
                'camel'
            )
        )
