# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from typing import (
    Any,
    Literal,
    TYPE_CHECKING
)
from dataclasses import (
    dataclass
)

if TYPE_CHECKING:
    from cdp.domains.dom.types import (
        BackendNodeId,
        Rect
    )

LayerId = str
SnapshotId = str
PaintProfile = list[float]

@dataclass
class ScrollRect:
    rect: 'Rect'
    type: str


@dataclass
class StickyPositionConstraint:
    sticky_box_rect: 'Rect'
    containing_block_rect: 'Rect'
    nearest_layer_shifting_sticky_box: 'LayerId'
    nearest_layer_shifting_containing_block: 'LayerId'


@dataclass
class PictureTile:
    x: float
    y: float
    picture: str


@dataclass
class Layer:
    layer_id: 'LayerId'
    parent_layer_id: 'LayerId'
    backend_node_id: 'BackendNodeId'
    offset_x: float
    offset_y: float
    width: float
    height: float
    transform: list[float]
    anchor_x: float
    anchor_y: float
    anchor_z: float
    paint_count: int
    draws_content: bool
    invisible: bool
    scroll_rects: list['ScrollRect']
    sticky_position_constraint: 'StickyPositionConstraint'


@dataclass
class CompositingReasonsReturnT:
    compositing_reasons: list
    compositing_reason_ids: list


@dataclass
class LoadSnapshotReturnT:
    snapshot_id: 'SnapshotId'


@dataclass
class MakeSnapshotReturnT:
    snapshot_id: 'SnapshotId'


@dataclass
class ProfileSnapshotReturnT:
    timings: list


@dataclass
class ReplaySnapshotReturnT:
    data_url: str


@dataclass
class SnapshotCommandLogReturnT:
    command_log: list
