# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.domains.base import (
    BaseDomain
)
from cdp.domains import (
    mappers
)
from cdp.utils import (
    UNDEFINED,
    is_defined
)
from dataclasses import (
    dataclass
)
from typing import (
    TYPE_CHECKING
)
from cdp.domains.browser.types import (
    Bounds,
    BrowserCommandId,
    BrowserContextID,
    GetBrowserCommandLineReturnType,
    GetHistogramReturnType,
    GetHistogramsReturnType,
    GetVersionReturnType,
    GetWindowBoundsReturnType,
    GetWindowForTargetReturnType,
    PermissionDescriptor,
    PermissionSetting,
    TargetID,
    WindowID
)
if TYPE_CHECKING:
    from cdp.target.connection import (
        IFutureResponse
    )


@dataclass
class Browser(BaseDomain):
    def set_permission(
            self,
            permission: 'PermissionDescriptor',
            setting: 'PermissionSetting',
            origin: 'str' = UNDEFINED,
            browser_context_id: 'BrowserContextID' = UNDEFINED
    ) -> 'IFutureResponse[None]':
        params = {
            'permission': to_dict(
                permission,
                'camel'
            ),
            'setting': to_dict(
                setting,
                'camel'
            ),
        }

        if is_defined(origin):
            params['origin'] = origin

        if is_defined(browser_context_id):
            params['browserContextId'] = to_dict(
                browser_context_id,
                'camel'
            )

        return self._send_command(
            'Browser.setPermission',
            params,
            False
        )

    def grant_permissions(
            self,
            permissions: 'list',
            origin: 'str' = UNDEFINED,
            browser_context_id: 'BrowserContextID' = UNDEFINED
    ) -> 'IFutureResponse[None]':
        params = {
            'permissions': permissions,
        }

        if is_defined(origin):
            params['origin'] = origin

        if is_defined(browser_context_id):
            params['browserContextId'] = to_dict(
                browser_context_id,
                'camel'
            )

        return self._send_command(
            'Browser.grantPermissions',
            params,
            False
        )

    def reset_permissions(
            self,
            browser_context_id: 'BrowserContextID' = UNDEFINED
    ) -> 'IFutureResponse[None]':
        params = {}

        if is_defined(browser_context_id):
            params['browserContextId'] = to_dict(
                browser_context_id,
                'camel'
            )

        return self._send_command(
            'Browser.resetPermissions',
            params,
            False
        )

    def set_download_behavior(
            self,
            behavior: 'str',
            browser_context_id: 'BrowserContextID' = UNDEFINED,
            download_path: 'str' = UNDEFINED,
            events_enabled: 'bool' = UNDEFINED
    ) -> 'IFutureResponse[None]':
        params = {
            'behavior': behavior,
        }

        if is_defined(browser_context_id):
            params['browserContextId'] = to_dict(
                browser_context_id,
                'camel'
            )

        if is_defined(download_path):
            params['downloadPath'] = download_path

        if is_defined(events_enabled):
            params['eventsEnabled'] = events_enabled

        return self._send_command(
            'Browser.setDownloadBehavior',
            params,
            False
        )

    def cancel_download(
            self,
            guid: 'str',
            browser_context_id: 'BrowserContextID' = UNDEFINED
    ) -> 'IFutureResponse[None]':
        params = {
            'guid': guid,
        }

        if is_defined(browser_context_id):
            params['browserContextId'] = to_dict(
                browser_context_id,
                'camel'
            )

        return self._send_command(
            'Browser.cancelDownload',
            params,
            False
        )

    def close(
            self
    ) -> 'IFutureResponse[None]':
        params = {}

        return self._send_command(
            'Browser.close',
            params,
            False
        )

    def crash(
            self
    ) -> 'IFutureResponse[None]':
        params = {}

        return self._send_command(
            'Browser.crash',
            params,
            False
        )

    def crash_gpu_process(
            self
    ) -> 'IFutureResponse[None]':
        params = {}

        return self._send_command(
            'Browser.crashGpuProcess',
            params,
            False
        )

    def get_version(
            self
    ) -> 'IFutureResponse[GetVersionReturnType]':
        params = {}

        return self._send_command(
            'Browser.getVersion',
            params,
            True,
            lambda data: from_dict(
                GetVersionReturnType,
                data,
                'camel'
            )
        )

    def get_browser_command_line(
            self
    ) -> 'IFutureResponse[GetBrowserCommandLineReturnType]':
        params = {}

        return self._send_command(
            'Browser.getBrowserCommandLine',
            params,
            True,
            lambda data: from_dict(
                GetBrowserCommandLineReturnType,
                data,
                'camel'
            )
        )

    def get_histograms(
            self,
            query: 'str' = UNDEFINED,
            delta: 'bool' = UNDEFINED
    ) -> 'IFutureResponse[GetHistogramsReturnType]':
        params = {}

        if is_defined(query):
            params['query'] = query

        if is_defined(delta):
            params['delta'] = delta

        return self._send_command(
            'Browser.getHistograms',
            params,
            True,
            lambda data: from_dict(
                GetHistogramsReturnType,
                data,
                'camel'
            )
        )

    def get_histogram(
            self,
            name: 'str',
            delta: 'bool' = UNDEFINED
    ) -> 'IFutureResponse[GetHistogramReturnType]':
        params = {
            'name': name,
        }

        if is_defined(delta):
            params['delta'] = delta

        return self._send_command(
            'Browser.getHistogram',
            params,
            True,
            lambda data: from_dict(
                GetHistogramReturnType,
                data,
                'camel'
            )
        )

    def get_window_bounds(
            self,
            window_id: 'WindowID'
    ) -> 'IFutureResponse[GetWindowBoundsReturnType]':
        params = {
            'windowId': to_dict(
                window_id,
                'camel'
            ),
        }

        return self._send_command(
            'Browser.getWindowBounds',
            params,
            True,
            lambda data: from_dict(
                GetWindowBoundsReturnType,
                data,
                'camel'
            )
        )

    def get_window_for_target(
            self,
            target_id: 'TargetID' = UNDEFINED
    ) -> 'IFutureResponse[GetWindowForTargetReturnType]':
        params = {}

        if is_defined(target_id):
            params['targetId'] = to_dict(
                target_id,
                'camel'
            )

        return self._send_command(
            'Browser.getWindowForTarget',
            params,
            True,
            lambda data: from_dict(
                GetWindowForTargetReturnType,
                data,
                'camel'
            )
        )

    def set_window_bounds(
            self,
            window_id: 'WindowID',
            bounds: 'Bounds'
    ) -> 'IFutureResponse[None]':
        params = {
            'windowId': to_dict(
                window_id,
                'camel'
            ),
            'bounds': to_dict(
                bounds,
                'camel'
            ),
        }

        return self._send_command(
            'Browser.setWindowBounds',
            params,
            False
        )

    def set_dock_tile(
            self,
            badge_label: 'str' = UNDEFINED,
            image: 'str' = UNDEFINED
    ) -> 'IFutureResponse[None]':
        params = {}

        if is_defined(badge_label):
            params['badgeLabel'] = badge_label

        if is_defined(image):
            params['image'] = image

        return self._send_command(
            'Browser.setDockTile',
            params,
            False
        )

    def execute_browser_command(
            self,
            command_id: 'BrowserCommandId'
    ) -> 'IFutureResponse[None]':
        params = {
            'commandId': to_dict(
                command_id,
                'camel'
            ),
        }

        return self._send_command(
            'Browser.executeBrowserCommand',
            params,
            False
        )

    def add_privacy_sandbox_enrollment_override(
            self,
            url: 'str'
    ) -> 'IFutureResponse[None]':
        params = {
            'url': url,
        }

        return self._send_command(
            'Browser.addPrivacySandboxEnrollmentOverride',
            params,
            False
        )
