# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.domains.base import (
    BaseDomain
)
from dataclasses import (
    dataclass
)
from cdp.utils import (
    is_defined,
    UNDEFINED
)
from cdp.domains.system_info.types import (
    GetFeatureStateReturnT,
    GetInfoReturnT,
    GetProcessInfoReturnT
)
if TYPE_CHECKING:
    from cdp.target.connection import (
        IResult
    )


@dataclass
class SystemInfo(BaseDomain):
    def get_info(
            self
    ) -> IResult['GetInfoReturnT']:
        params = {}

        return self._send_command(
            'SystemInfo.getInfo',
            params,
            True
        )

    def get_feature_state(
            self,
            feature_state: str
    ) -> IResult['GetFeatureStateReturnT']:
        params = {
            'featureState': feature_state,
        }

        return self._send_command(
            'SystemInfo.getFeatureState',
            params,
            True
        )

    def get_process_info(
            self
    ) -> IResult['GetProcessInfoReturnT']:
        params = {}

        return self._send_command(
            'SystemInfo.getProcessInfo',
            params,
            True
        )
