"""
DO NOT EDIT THIS FILE!

This file is generated from the CDP specification. If you need to
make changes, edit the generator and regenerate the modules.

This domain provides various functionality related to drawing atop the inspected page.
"""