# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from dataclasses import (
    dataclass
)
from typing import (
    TYPE_CHECKING
)
from typing import (
    Any
)


@dataclass
class ConsoleMessage:
    source: str
    level: str
    text: str
    url: str
    line: int
    column: int
