# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.types import (
    network,
    service_worker
)
from typing import (
    Literal,
    TypedDict
)

ServiceName = Literal[
    'backgroundFetch',
    'backgroundSync',
    'pushMessaging',
    'notifications',
    'paymentHandler',
    'periodicBackgroundSync'
]


class EventMetadata(TypedDict):
    key: str
    value: str


class BackgroundServiceEvent(TypedDict):
    timestamp: 'network.TimeSinceEpoch'
    origin: str
    serviceWorkerRegistrationId: 'service_worker.RegistrationID'
    service: 'ServiceName'
    eventName: str
    instanceId: str
    eventMetadata: list
    storageKey: str
