# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.types import (
    storage
)
from typing import (
    Literal,
    TypedDict
)

CacheId = str

CachedResponseType = Literal[
    'basic',
    'cors',
    'default',
    'error',
    'opaqueResponse',
    'opaqueRedirect'
]


class DataEntry(TypedDict):
    requestURL: str
    requestMethod: str
    requestHeaders: list
    responseTime: float
    responseStatus: int
    responseStatusText: str
    responseType: 'CachedResponseType'
    responseHeaders: list


class Cache(TypedDict):
    cacheId: 'CacheId'
    securityOrigin: str
    storageKey: str
    cacheName: str
    storageBucket: 'storage.StorageBucket'


class Header(TypedDict):
    name: str
    value: str


class CachedResponse(TypedDict):
    body: str
