# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.
from cdp.types import (
    runtime
)
from typing import (
    Literal,
    NotRequired,
    TypedDict
)

HeapSnapshotObjectId = str


class SamplingHeapProfileNode(TypedDict):
    call_frame: 'runtime.CallFrame'
    self_size: float
    id: int
    children: list


class SamplingHeapProfileSample(TypedDict):
    size: float
    node_id: int
    ordinal: float


class SamplingHeapProfile(TypedDict):
    head: 'SamplingHeapProfileNode'
    samples: list


class AddInspectedHeapObjectParamsT(TypedDict):
    heap_object_id: 'HeapSnapshotObjectId'


class GetHeapObjectIdParamsT(TypedDict):
    object_id: 'runtime.RemoteObjectId'


class GetObjectByHeapObjectIdParamsT(TypedDict):
    object_id: 'HeapSnapshotObjectId'
    object_group: NotRequired[str]


class StartSamplingParamsT(TypedDict):
    sampling_interval: NotRequired[float]


class StartTrackingHeapObjectsParamsT(TypedDict):
    track_allocations: NotRequired[bool]


class StopTrackingHeapObjectsParamsT(TypedDict):
    report_progress: NotRequired[bool]


class TakeHeapSnapshotParamsT(TypedDict):
    report_progress: NotRequired[bool]


class GetHeapObjectIdReturnT(TypedDict):
    heap_snapshot_object_id: 'HeapSnapshotObjectId'


class GetObjectByHeapObjectIdReturnT(TypedDict):
    result: 'runtime.RemoteObject'


class GetSamplingProfileReturnT(TypedDict):
    profile: 'SamplingHeapProfile'


class StopSamplingReturnT(TypedDict):
    profile: 'SamplingHeapProfile'


class AddHeapSnapshotChunkEventT(TypedDict):
    name: Literal['add_heap_snapshot_chunk']
    params: 'AddHeapSnapshotChunkParamsT'


class HeapStatsUpdateEventT(TypedDict):
    name: Literal['heap_stats_update']
    params: 'HeapStatsUpdateParamsT'


class LastSeenObjectIdEventT(TypedDict):
    name: Literal['last_seen_object_id']
    params: 'LastSeenObjectIdParamsT'


class ReportHeapSnapshotProgressEventT(TypedDict):
    name: Literal['report_heap_snapshot_progress']
    params: 'ReportHeapSnapshotProgressParamsT'


class ResetProfilesEventT(TypedDict):
    name: Literal['reset_profiles']
    params: None


class AddHeapSnapshotChunkParamsT(TypedDict):
    chunk: str


class HeapStatsUpdateParamsT(TypedDict):
    stats_update: list


class LastSeenObjectIdParamsT(TypedDict):
    last_seen_object_id: int
    timestamp: float


class ReportHeapSnapshotProgressParamsT(TypedDict):
    done: int
    total: int
    finished: bool
