# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.types import (
    debugger,
    dom,
    emulation,
    io,
    network,
    runtime
)
from typing import (
    Literal,
    TypedDict
)

FrameId = str

ScriptIdentifier = str

AdFrameType = Literal[
    'none',
    'child',
    'root'
]

AdFrameExplanation = Literal[
    'ParentIsAd',
    'CreatedByAdScript',
    'MatchedBlockingRule'
]

SecureContextType = Literal[
    'Secure',
    'SecureLocalhost',
    'InsecureScheme',
    'InsecureAncestor'
]

CrossOriginIsolatedContextType = Literal[
    'Isolated',
    'NotIsolated',
    'NotIsolatedFeatureDisabled'
]

GatedAPIFeatures = Literal[
    'SharedArrayBuffers',
    'SharedArrayBuffersTransferAllowed',
    'PerformanceMeasureMemory',
    'PerformanceProfile'
]

PermissionsPolicyFeature = Literal[
    'accelerometer',
    'ambient-light-sensor',
    'attribution-reporting',
    'autoplay',
    'bluetooth',
    'browsing-topics',
    'camera',
    'ch-dpr',
    'ch-device-memory',
    'ch-downlink',
    'ch-ect',
    'ch-prefers-color-scheme',
    'ch-prefers-reduced-motion',
    'ch-prefers-reduced-transparency',
    'ch-rtt',
    'ch-save-data',
    'ch-ua',
    'ch-ua-arch',
    'ch-ua-bitness',
    'ch-ua-platform',
    'ch-ua-model',
    'ch-ua-mobile',
    'ch-ua-form-factor',
    'ch-ua-full-version',
    'ch-ua-full-version-list',
    'ch-ua-platform-version',
    'ch-ua-wow64',
    'ch-viewport-height',
    'ch-viewport-width',
    'ch-width',
    'clipboard-read',
    'clipboard-write',
    'compute-pressure',
    'cross-origin-isolated',
    'direct-sockets',
    'display-capture',
    'document-domain',
    'encrypted-media',
    'execution-while-out-of-viewport',
    'execution-while-not-rendered',
    'focus-without-user-activation',
    'fullscreen',
    'frobulate',
    'gamepad',
    'geolocation',
    'gyroscope',
    'hid',
    'identity-credentials-get',
    'idle-detection',
    'interest-cohort',
    'join-ad-interest-group',
    'keyboard-map',
    'local-fonts',
    'magnetometer',
    'microphone',
    'midi',
    'otp-credentials',
    'payment',
    'picture-in-picture',
    'private-aggregation',
    'private-state-token-issuance',
    'private-state-token-redemption',
    'publickey-credentials-get',
    'run-ad-auction',
    'screen-wake-lock',
    'serial',
    'shared-autofill',
    'shared-storage',
    'shared-storage-select-url',
    'smart-card',
    'storage-access',
    'sync-xhr',
    'unload',
    'usb',
    'vertical-scroll',
    'web-share',
    'window-management',
    'window-placement',
    'xr-spatial-tracking'
]

PermissionsPolicyBlockReason = Literal[
    'Header',
    'IframeAttribute',
    'InFencedFrameTree',
    'InIsolatedApp'
]

OriginTrialTokenStatus = Literal[
    'Success',
    'NotSupported',
    'Insecure',
    'Expired',
    'WrongOrigin',
    'InvalidSignature',
    'Malformed',
    'WrongVersion',
    'FeatureDisabled',
    'TokenDisabled',
    'FeatureDisabledForUser',
    'UnknownTrial'
]

OriginTrialStatus = Literal[
    'Enabled',
    'ValidTokenNotProvided',
    'OSNotSupported',
    'TrialNotAllowed'
]

OriginTrialUsageRestriction = Literal[
    'None',
    'Subset'
]

TransitionType = Literal[
    'link',
    'typed',
    'address_bar',
    'auto_bookmark',
    'auto_subframe',
    'manual_subframe',
    'generated',
    'auto_toplevel',
    'form_submit',
    'reload',
    'keyword',
    'keyword_generated',
    'other'
]

DialogType = Literal[
    'alert',
    'confirm',
    'prompt',
    'beforeunload'
]

ClientNavigationReason = Literal[
    'formSubmissionGet',
    'formSubmissionPost',
    'httpHeaderRefresh',
    'scriptInitiated',
    'metaTagRefresh',
    'pageBlockInterstitial',
    'reload',
    'anchorClick'
]

ClientNavigationDisposition = Literal[
    'currentTab',
    'newTab',
    'newWindow',
    'download'
]

ReferrerPolicy = Literal[
    'noReferrer',
    'noReferrerWhenDowngrade',
    'origin',
    'originWhenCrossOrigin',
    'sameOrigin',
    'strictOrigin',
    'strictOriginWhenCrossOrigin',
    'unsafeUrl'
]

AutoResponseMode = Literal[
    'none',
    'autoAccept',
    'autoReject',
    'autoOptOut'
]

NavigationType = Literal[
    'Navigation',
    'BackForwardCacheRestore'
]

BackForwardCacheNotRestoredReason = Literal[
    'NotPrimaryMainFrame',
    'BackForwardCacheDisabled',
    'RelatedActiveContentsExist',
    'HTTPStatusNotOK',
    'SchemeNotHTTPOrHTTPS',
    'Loading',
    'WasGrantedMediaAccess',
    'DisableForRenderFrameHostCalled',
    'DomainNotAllowed',
    'HTTPMethodNotGET',
    'SubframeIsNavigating',
    'Timeout',
    'CacheLimit',
    'JavaScriptExecution',
    'RendererProcessKilled',
    'RendererProcessCrashed',
    'SchedulerTrackedFeatureUsed',
    'ConflictingBrowsingInstance',
    'CacheFlushed',
    'ServiceWorkerVersionActivation',
    'SessionRestored',
    'ServiceWorkerPostMessage',
    'EnteredBackForwardCacheBeforeServiceWorkerHostAdded',
    'RenderFrameHostReused_SameSite',
    'RenderFrameHostReused_CrossSite',
    'ServiceWorkerClaim',
    'IgnoreEventAndEvict',
    'HaveInnerContents',
    'TimeoutPuttingInCache',
    'BackForwardCacheDisabledByLowMemory',
    'BackForwardCacheDisabledByCommandLine',
    'NetworkRequestDatapipeDrainedAsBytesConsumer',
    'NetworkRequestRedirected',
    'NetworkRequestTimeout',
    'NetworkExceedsBufferLimit',
    'NavigationCancelledWhileRestoring',
    'NotMostRecentNavigationEntry',
    'BackForwardCacheDisabledForPrerender',
    'UserAgentOverrideDiffers',
    'ForegroundCacheLimit',
    'BrowsingInstanceNotSwapped',
    'BackForwardCacheDisabledForDelegate',
    'UnloadHandlerExistsInMainFrame',
    'UnloadHandlerExistsInSubFrame',
    'ServiceWorkerUnregistration',
    'CacheControlNoStore',
    'CacheControlNoStoreCookieModified',
    'CacheControlNoStoreHTTPOnlyCookieModified',
    'NoResponseHead',
    'Unknown',
    'ActivationNavigationsDisallowedForBug1234857',
    'ErrorDocument',
    'FencedFramesEmbedder',
    'CookieDisabled',
    'HTTPAuthRequired',
    'CookieFlushed',
    'WebSocket',
    'WebTransport',
    'WebRTC',
    'MainResourceHasCacheControlNoStore',
    'MainResourceHasCacheControlNoCache',
    'SubresourceHasCacheControlNoStore',
    'SubresourceHasCacheControlNoCache',
    'ContainsPlugins',
    'DocumentLoaded',
    'DedicatedWorkerOrWorklet',
    'OutstandingNetworkRequestOthers',
    'RequestedMIDIPermission',
    'RequestedAudioCapturePermission',
    'RequestedVideoCapturePermission',
    'RequestedBackForwardCacheBlockedSensors',
    'RequestedBackgroundWorkPermission',
    'BroadcastChannel',
    'WebXR',
    'SharedWorker',
    'WebLocks',
    'WebHID',
    'WebShare',
    'RequestedStorageAccessGrant',
    'WebNfc',
    'OutstandingNetworkRequestFetch',
    'OutstandingNetworkRequestXHR',
    'AppBanner',
    'Printing',
    'WebDatabase',
    'PictureInPicture',
    'Portal',
    'SpeechRecognizer',
    'IdleManager',
    'PaymentManager',
    'SpeechSynthesis',
    'KeyboardLock',
    'WebOTPService',
    'OutstandingNetworkRequestDirectSocket',
    'InjectedJavascript',
    'InjectedStyleSheet',
    'KeepaliveRequest',
    'IndexedDBEvent',
    'Dummy',
    'JsNetworkRequestReceivedCacheControlNoStoreResource',
    'WebRTCSticky',
    'WebTransportSticky',
    'WebSocketSticky',
    'ContentSecurityHandler',
    'ContentWebAuthenticationAPI',
    'ContentFileChooser',
    'ContentSerial',
    'ContentFileSystemAccess',
    'ContentMediaDevicesDispatcherHost',
    'ContentWebBluetooth',
    'ContentWebUSB',
    'ContentMediaSessionService',
    'ContentScreenReader',
    'EmbedderPopupBlockerTabHelper',
    'EmbedderSafeBrowsingTriggeredPopupBlocker',
    'EmbedderSafeBrowsingThreatDetails',
    'EmbedderAppBannerManager',
    'EmbedderDomDistillerViewerSource',
    'EmbedderDomDistillerSelfDeletingRequestDelegate',
    'EmbedderOomInterventionTabHelper',
    'EmbedderOfflinePage',
    'EmbedderChromePasswordManagerClientBindCredentialManager',
    'EmbedderPermissionRequestManager',
    'EmbedderModalDialog',
    'EmbedderExtensions',
    'EmbedderExtensionMessaging',
    'EmbedderExtensionMessagingForOpenPort',
    'EmbedderExtensionSentMessageToCachedFrame'
]

BackForwardCacheNotRestoredReasonType = Literal[
    'SupportPending',
    'PageSupportNeeded',
    'Circumstantial'
]


class AdFrameStatus(TypedDict):
    adFrameType: 'AdFrameType'
    explanations: list


class AdScriptId(TypedDict):
    scriptId: 'runtime.ScriptId'
    debuggerId: 'runtime.UniqueDebuggerId'


class PermissionsPolicyBlockLocator(TypedDict):
    frameId: 'FrameId'
    blockReason: 'PermissionsPolicyBlockReason'


class PermissionsPolicyFeatureState(TypedDict):
    feature: 'PermissionsPolicyFeature'
    allowed: bool
    locator: 'PermissionsPolicyBlockLocator'


class OriginTrialToken(TypedDict):
    origin: str
    matchSubDomains: bool
    trialName: str
    expiryTime: 'network.TimeSinceEpoch'
    isThirdParty: bool
    usageRestriction: 'OriginTrialUsageRestriction'


class OriginTrialTokenWithStatus(TypedDict):
    rawTokenText: str
    status: 'OriginTrialTokenStatus'
    parsedToken: 'OriginTrialToken'


class OriginTrial(TypedDict):
    trialName: str
    status: 'OriginTrialStatus'
    tokensWithStatus: list


class Frame(TypedDict):
    id: 'FrameId'
    loaderId: 'network.LoaderId'
    url: str
    domainAndRegistry: str
    securityOrigin: str
    mimeType: str
    secureContextType: 'SecureContextType'
    crossOriginIsolatedContextType: 'CrossOriginIsolatedContextType'
    gatedAPIFeatures: list
    parentId: 'FrameId'
    name: str
    urlFragment: str
    unreachableUrl: str
    adFrameStatus: 'AdFrameStatus'


class FrameResource(TypedDict):
    url: str
    type: 'network.ResourceType'
    mimeType: str
    lastModified: 'network.TimeSinceEpoch'
    contentSize: float
    failed: bool
    canceled: bool


class FrameResourceTree(TypedDict):
    frame: 'Frame'
    resources: list
    childFrames: list


class FrameTree(TypedDict):
    frame: 'Frame'
    childFrames: list


class NavigationEntry(TypedDict):
    id: int
    url: str
    userTypedURL: str
    title: str
    transitionType: 'TransitionType'


class ScreencastFrameMetadata(TypedDict):
    offsetTop: float
    pageScaleFactor: float
    deviceWidth: float
    deviceHeight: float
    scrollOffsetX: float
    scrollOffsetY: float
    timestamp: 'network.TimeSinceEpoch'


class AppManifestError(TypedDict):
    message: str
    critical: int
    line: int
    column: int


class AppManifestParsedProperties(TypedDict):
    scope: str


class LayoutViewport(TypedDict):
    pageX: int
    pageY: int
    clientWidth: int
    clientHeight: int


class VisualViewport(TypedDict):
    offsetX: float
    offsetY: float
    pageX: float
    pageY: float
    clientWidth: float
    clientHeight: float
    scale: float
    zoom: float


class Viewport(TypedDict):
    x: float
    y: float
    width: float
    height: float
    scale: float


class FontFamilies(TypedDict):
    standard: str
    fixed: str
    serif: str
    sansSerif: str
    cursive: str
    fantasy: str
    math: str


class ScriptFontFamilies(TypedDict):
    script: str
    fontFamilies: 'FontFamilies'


class FontSizes(TypedDict):
    standard: int
    fixed: int


class InstallabilityErrorArgument(TypedDict):
    name: str
    value: str


class InstallabilityError(TypedDict):
    errorId: str
    errorArguments: list


class CompilationCacheParams(TypedDict):
    url: str
    eager: bool


class BackForwardCacheNotRestoredExplanation(TypedDict):
    type: 'BackForwardCacheNotRestoredReasonType'
    reason: 'BackForwardCacheNotRestoredReason'
    context: str


class BackForwardCacheNotRestoredExplanationTree(TypedDict):
    url: str
    explanations: list
    children: list
