# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.types import (
    dom,
    network,
    page
)
from typing import (
    TypedDict
)


class LargestContentfulPaint(TypedDict):
    render_time: 'network.TimeSinceEpoch'
    load_time: 'network.TimeSinceEpoch'
    size: float
    element_id: str
    url: str
    node_id: 'dom.BackendNodeId'


class LayoutShiftAttribution(TypedDict):
    previous_rect: 'dom.Rect'
    current_rect: 'dom.Rect'
    node_id: 'dom.BackendNodeId'


class LayoutShift(TypedDict):
    value: float
    had_recent_input: bool
    last_input_time: 'network.TimeSinceEpoch'
    sources: list


class TimelineEvent(TypedDict):
    frame_id: 'page.FrameId'
    type: str
    name: str
    time: 'network.TimeSinceEpoch'
    duration: float
    lcp_details: 'LargestContentfulPaint'
    layout_shift_details: 'LayoutShift'
