# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from typing import (
    Literal,
    TypedDict
)

AuthenticatorId = str

AuthenticatorProtocol = Literal[
    'u2f',
    'ctap2'
]

Ctap2Version = Literal[
    'ctap2_0',
    'ctap2_1'
]

AuthenticatorTransport = Literal[
    'usb',
    'nfc',
    'ble',
    'cable',
    'internal'
]


class VirtualAuthenticatorOptions(TypedDict):
    protocol: 'AuthenticatorProtocol'
    transport: 'AuthenticatorTransport'
    ctap2Version: 'Ctap2Version'
    hasResidentKey: bool
    hasUserVerification: bool
    hasLargeBlob: bool
    hasCredBlob: bool
    hasMinPinLength: bool
    hasPrf: bool
    automaticPresenceSimulation: bool
    isUserVerified: bool


class Credential(TypedDict):
    credentialId: str
    isResidentCredential: bool
    privateKey: str
    signCount: int
    rpId: str
    userHandle: str
    largeBlob: str
