# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from cdp.domains.base import (
    BaseDomain
)
from dataclasses import (
    dataclass
)
from cdp.utils import (
    is_defined,
    UNDEFINED
)
from cdp.domains.database.types import (
    DatabaseId,
    ExecuteSQLReturnT,
    GetDatabaseTableNamesReturnT
)
if TYPE_CHECKING:
    from cdp.target.connection import (
        IResult
    )


@dataclass
class Database(BaseDomain):
    def disable(
            self
    ) -> IResult[None]:
        params = {}

        return self._send_command(
            'Database.disable',
            params,
            False
        )

    def enable(
            self
    ) -> IResult[None]:
        params = {}

        return self._send_command(
            'Database.enable',
            params,
            False
        )

    def execute_sql(
            self,
            database_id: DatabaseId,
            query: str
    ) -> IResult['ExecuteSQLReturnT']:
        params = {
            'databaseId': database_id,
            'query': query,
        }

        return self._send_command(
            'Database.executeSQL',
            params,
            True
        )

    def get_database_table_names(
            self,
            database_id: DatabaseId
    ) -> IResult['GetDatabaseTableNamesReturnT']:
        params = {
            'databaseId': database_id,
        }

        return self._send_command(
            'Database.getDatabaseTableNames',
            params,
            True
        )
