# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from dataclasses import (
    dataclass
)
from typing import (
    TYPE_CHECKING
)
from typing import (
    Any
)


@dataclass
class Domain:
    name: str
    version: str
    def to_dict(
        self,
        casing_strategy: Literal[
            'snake',
            'camel',
            'pascal'
] = 'snake'
    ):

        if casing_strategy == 'snake':
            return {
                'name': self.name,
                'version': self.version,
            }
        if casing_strategy == 'snake':
            return {
                'name': self.name,
                'version': self.version,
            }
        if casing_strategy == 'snake':
            return {
                'Name': self.name,
                'Version': self.version,
            }


@dataclass
class GetDomainsReturnT:
    domains: list
