# DO NOT EDIT THIS FILE
#
# This file is generated by the generator. To make changes, edit the generator
# and run it again.

from dataclasses import (
    dataclass
)
from typing import (
    TYPE_CHECKING
)
from typing import (
    Any
)


@dataclass
class ScreenshotParams:
    format: str
    quality: int
    optimize_for_speed: bool
    def to_dict(
        self,
        casing_strategy: Literal[
            'snake',
            'camel',
            'pascal'
] = 'snake'
    ):

        if casing_strategy == 'snake':
            return {
                'format': self.format_,
                'quality': self.quality,
                'optimize_for_speed': self.optimize_for_speed,
            }
        if casing_strategy == 'snake':
            return {
                'format': self.format_,
                'quality': self.quality,
                'optimizeForSpeed': self.optimize_for_speed,
            }
        if casing_strategy == 'snake':
            return {
                'Format': self.format_,
                'Quality': self.quality,
                'OptimizeForSpeed': self.optimize_for_speed,
            }


@dataclass
class BeginFrameReturnT:
    has_damage: bool
    screenshot_data: str
